### PR TITLE
Create COPYING

### PR DESCRIPTION
**Pull request by kghbln**
Add COPYING file with GPL-2.0-or-later since this is the license that governs most of the extensions included.

### CODE REVIEW

**Comment by JeroenDeDauw** [comment]
Thanks! Guess I did a forgetti

This needs to match https://github.com/SemanticMediaWiki/SemanticBundle/blob/master/composer.json#L12 which it does.

**Comment by JeroenDeDauw** [comment]
Omg now more than 50% of the lines in this package are legal goop :D

**Comment by kghbln** [comment]
> This needs to match https://github.com/SemanticMediaWiki/SemanticBundle/blob/master/composer.json#L12 which it does.

Did not look at this but the choice appeared to be pretty obvious.

> Omg now more than 50% of the lines in this package are legal goop :D

Now I have more lines in here than you. :P

**Comment by JeroenDeDauw** [comment]
> Now I have more lines in here than you. :P

Did you just volunteer to maintain this repo? That's very nice. Thank you!

;)

**Pull request merged**
